version: "3.9"

services:
  db:
    image: postgres:15
    container_name: fluxrent_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tenantdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: fluxrent_redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fluxrent_backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py loaddata seed_data.json || true &&
             gunicorn fluxrent.wsgi:application --bind 0.0.0.0:4000 --workers 4"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "4000:4000"

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fluxrent_celery
    command: celery -A fluxrent.celery:app worker --loglevel=info --concurrency=2
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - backend
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fluxrent_frontend
    env_file:
      - .env
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
