version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
